---
kind: pipeline
type: docker
name: Publish to registry
steps:
  - name: Build & push
    image: plugins/docker
    settings:
      repo: registry.sebele.io/gbch3
      registry: registry.sebele.io
    tags: [ "latest" ]  

---
kind: pipeline
type: docker
name: Deploy to production
trigger:
  target: [ production ]
depends_on: [ "Publish to registry" ]
clone:
  disable: true
steps:
- name: Deploy
  image: appleboy/drone-ssh
  settings:
      host: sebele.io
      username: deploy
      port: 2222
      key:
        from_secret: deploy_ssh_key
      script:
        - cd gbch3
        - docker-compose pull --quiet production
        - docker-compose up -d production